// Shared by client-side pre-checks and server-side enforcement. Kept under the
// ~4.5 MB request-body limit of common serverless hosts.
export const IMAGE_MAX_BYTES = 4 * 1024 * 1024;
export const RESUME_MAX_BYTES = 4 * 1024 * 1024;

// Videos upload straight from the browser to Cloudinary, so they aren't bound
// by the serverless body limit.
export const VIDEO_MAX_BYTES = 50 * 1024 * 1024;
export const VIDEO_FORMATS = ["mp4", "webm", "mov", "m4v"] as const;
export const VIDEO_ACCEPT = "video/mp4,video/webm,video/quicktime,video/x-m4v,.mp4,.webm,.mov,.m4v";
export const VIDEO_FOLDER = "videos";
/** Web-playback rendition generated by Cloudinary at upload (eager, async). */
export const VIDEO_PLAYBACK_TRANSFORM = "q_auto,w_1280,c_limit";

/**
 * Candidate sources for a project video: the compressed Cloudinary rendition
 * first, then the original (used until the rendition is ready, or for
 * non-Cloudinary URLs).
 */
export function videoSources(url: string): string[] {
  const match = /^(https:\/\/res\.cloudinary\.com\/[^/]+\/video\/upload\/)(v\d+\/.+)$/.exec(url);
  if (!match) return [url];
  const optimized = `${match[1]}${VIDEO_PLAYBACK_TRANSFORM}/${match[2]!.replace(/\.[a-z0-9]+$/i, ".mp4")}`;
  return [optimized, url];
}

export const IMAGE_ACCEPT = "image/jpeg,image/png,image/webp,image/gif,image/avif";
export const IMAGE_MIME_TYPES = IMAGE_ACCEPT.split(",");

export const IMAGE_FOLDERS = [
  "projects",
  "profile",
  "logos",
  "certifications",
  "skills",
  "hackathons",
] as const;
export type ImageFolder = (typeof IMAGE_FOLDERS)[number];
